name: Spread
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  snap-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build snap
        uses: snapcore/action-build@v1
        id: charmcraft
      - name: Upload snap artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.charmcraft.outputs.snap }}

  snap-tests:
    runs-on: self-hosted
    needs: [snap-build]
    strategy:
      fail-fast: false
      matrix:
        spread:
          - "google:"
          - "google:ubuntu-22.04-64:tests/spread/charms/k8s-operator:prometheus"

    steps:
      - name: Cleanup job workspace
        run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - name: Checkout charmcraft
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Download snap artifact
        uses: actions/download-artifact@v2
        with:
          name: snap
      - name: Run spread
        run: |
          spread ${{ matrix.spread }}
